[package]
name = "cleanup_module"
version = "0.1.0"
authors = ["Yuhanawa"]
edition = "2021"

[lib]
name = "CleanupModule"
crate-type = ["rlib", "dylib"]


[dependencies]
serde_json = "1.0.*"
globwalk = "0.8.*"
